### PR TITLE
restart shift interrupt duration with new pulse from gear sensor

### PR DESCRIPTION
**Pull request by aalm**
my shifter does allow changing  several gears at once(with single push, depending on how deep the push is) when going to smaller gear(bigger cog) on rear,
so the current version doesn't allow changing gears and going on throttle while it's still shifting.
it does seem as if the version that's being replaced with this can actually "drop" interrupt durations too - see the else if-case.
also changes the logic to clamp down for the whole duration, and not just if it was necessary in the beginning of the shift interrupt.

### CODE REVIEW

**Comment by kb79000** [comment]
Hi nice work possible to share .hex for bbs02b ? Thx 😉

**Comment by danielnilsson9** [comment]
Sounds like a good change, thank you! As I am unable to test this myself I will wait for some more feedback here before merging.

**Comment by kb79000** [comment]
Hi, I confirm that the optimization made for the gear change is really similar to the original bafang firmware nice job man !!! 😉

**Comment by danielnilsson9** [comment]
Thanks for testing. I'm happy with this change, looks clean, I will merge.

**Pull request merged**
