### PR TITLE
Add option to override configured assist level cadence when throttle …

### PR DESCRIPTION
**Pull request by danielnilsson9**
…overrides pas. #79

### CODE REVIEW

**Comment by danielnilsson9** [comment]
Needs testing before merge

**Comment by EigenMania** [comment]
I will test on my system tonight

**Comment by EigenMania** [comment]
I found one odd behavior, but maybe it is an edge case or intended. If you have Max Current and Max Throttle Current set to the same value, then you set throttle to 100%, you get 100% cadence. But then when you start pedalling slowly it drops back down to pedal cadence, and then depending on how Keep Current is configured it will switch back to 100% cadence once the Keep Current starts reducing power as a function of pedal cadence. Granted you have to ghost pedal to cause this, but it can cause a jerky unpredictable ride. Pretty sure this is the ">" in L451 of app.c. If switched to ">=" then you would consistently get 100% cadence whenever the throttle is maxed out (if Max Current and Max Throttle Current are both the same), regardless if you are pedalling or not. I'll see if I can test again this weekend to confirm.

**Comment by danielnilsson9** [comment]
Thanks you for for testing this, I think you are correct in that comparison causing an issue now. 

You didn't have any issue with a sudden surge of power when the the override kicked in? There is no ramp up implemented in this firmware (might be on the other mcu), maybe it is not needed.

As for 100% throttle => 100% cadence, that was the original suggestion when this issue came up in the endless sphere thread but some might not want this behaviour so a felt the flag was a pretty good trade off.

**Comment by EigenMania** [comment]
Much better now. I don't think any ramp-ups are needed. It's rather nice when the throttle is responsive, and reasonable current limits can also keep power surging in check. And if 100% cadence over-ride is too much, it can either be changed in the firmware, or in the future it could be in the config.

**Pull request merged**
